# -*- coding: utf-8 -*-
"""
/***************************************************************************
 upload
                                 A QGIS plugin
 upload file to server
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-02-19
        copyright            : (C) 2020 by Jozef Fábry
        email                : j.fabry24@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load upload class from file upload.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .upload import upload
    return upload(iface)
